# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0002_auto_20160623_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
