# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doit', '0003_auto_20160623_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
