# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0006_auto_20160623_1138'),
        ('doit', '0010_auto_20160623_1208'),
    ]

    operations = [
    ]
