# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0021_auto_20160627_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_info',
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
