# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0022_auto_20160627_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
