# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0025_auto_20160627_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=True),
        ),
    ]
