# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0026_auto_20160629_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
